### ISSUE TITLE
The "easysass.excludeRegex" diden't work.

### ISSUE THREAD

**Issue by wingmeng** [wojciechsura/easysass#11]
I spend a long time to find a extension which can build css from sass in VSCode. Until I found Easy Sass，it's really a great extension, but... why it not support sourcemap? And perhaps the "easysass.excludeRegex" setting has some promblem, it diden't work.
As shown in the figure, I want not to compile to “_” at the beginning of the sass file, so I set the "easysass.excludeRegex": "^[^_].+.s[c|a]ss", but it has no effect.
![vscode_screenshot](https://user-images.githubusercontent.com/9009389/29016355-bed5f21c-7b84-11e7-8045-bcecd9996520.png)

**Comment by wingmeng** [comment]
I don't know why the **underscore** in the above is filtered out

**Comment by hwangm** [comment]
If you are looking to exclude compiling of sass/scss like "_theme.scss", this is the regex I use: "_[a-z]+". Seems to work fine. I think that setting looks only at the filename without the extension.

**Comment by zhqgit** [comment]
"easysass.excludeRegex": "^_[a-z]+\\."

**Comment by zhqgit** [comment]
"easysass.excludeRegex": "^_[a-z]+\\."

**Comment by wingmeng** [comment]
@zhqgit 是的，这个好使，tks

**Comment by wingmeng** [comment]
` "easysass.excludeRegex": "^_+" `

**Comment by hongyu2016** [comment]
> 
"easysass.excludeRegex": "^_+"     这个不好使啊。没有效果

**Comment by hongyu2016** [comment]
> `"easysass.excludeRegex": "^_+"`

"easysass.excludeRegex": "^_+" 这个不好使啊。没有效果 @wingmeng
